### ISSUE TITLE
No module named 'dns'

### ISSUE THREAD

**Issue by therealOri** [Traumatism/Stick#1]
When trying to use stick with an IP I get the following error.

```bash
 - IP address
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'dns'"), traceback: Some(<traceback object at 0x7f6e9b4a1b40>) }', src/python.rs:92:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
__ __

<br />
<br />

When I try to pip install dns (because I believe this was a python module error) I get the following error.
```bash
ERROR: Could not find a version that satisfies the requirement dns (from versions: none)
ERROR: No matching distribution found for dns
```
__ __

<br />
<br />

I am not sure how to fix this error.

**Comment by therealOri** [comment]
All of this is immediately after just git cloning and building. (Following instructions)

Just the build and mv to current running directory commands

**Comment by Traumatism** [comment]
Yeah right I should make a feature to provide pythons modules list to install

pip install dnspython by the way

**Comment by therealOri** [comment]
Okay, ty!

**Comment by Traumatism** [comment]
the requirements file is now implemented!

fetch & pull
